Repository ucbpylegroup/RQpy, pull requests merged in 2019-01, with the labels that each got.

#25 Adding the baseline and the smoothed PSD RQs to processing, switch to using OptimumFilter class for most RQs
  rqpy/process/_process_rq.py
Labels: enhancement, refactor

#26 hist() and scatter() now support arbitrary numbers of cuts for plotting
  rqpy/plotting/_plotting.py
Labels: enhancement, refactor

#28 Iv analysis
  rqpy/core/__init__.py
  rqpy/core/_iv_didv_tools.py
  rqpy/plotting/_plotting.py
Labels: enhancement

#35 Added maxmin RQ, ending index for integral, and _check_of method to SetupRQ
  rqpy/process/_process_rq.py
Labels: enhancement

#38 Changed SetupRQ options, added new RQs
  rqpy/process/_process_rq.py
Labels: enhancement, refactor

#39 Low frequency chi^2 now calculated for pulse direction constrained RQs
  rqpy/process/_process_rq.py
Labels: enhancement

#41 Add Energy Absorbed RQ
  rqpy/process/_process_rq.py
Labels: enhancement

#42 Add fitting functionality to rqpy.binnedcut
  rqpy/core/_cut.py
Labels: enhancement

#43 Enhancement/energy cal
  rqpy/core/__init__.py
  rqpy/core/_energy_cal.py
  rqpy/core/_fitting.py
  rqpy/core/_rrq.py
  rqpy/plotting/_plotting.py
  rqpy/utils/_utils.py
Labels: enhancement

#44 rqpy.binnedcut fixes
  rqpy/core/_cut.py
Labels: bug, enhancement

#47 Changed rqpy.binnedcut output
  rqpy/core/_cut.py
  rqpy/plotting/_plotting.py
Labels: enhancement
