Repository ucbpylegroup/RQpy, pull requests merged in 2019-08, with the labels that each got.

#130 Add a constrained FIR trigger amplitude calculation, allow multichannel trigger simulation
  rqpy/process/_process_rq.py
  rqpy/sim/_trig_sim.py
Labels: feature

#131 Fix small bug in density plot, get rid of scientific notation for plotting
  rqpy/plotting/_core_plotting.py
Labels: bug, smallfix

#132 added lowpassgain as a parameter to get_train_gain
  rqpy/io/_load.py
Labels: smallfix

#133 Allow user to directly pass tau fall and tau rise guesses to processing nonlinear OF
  rqpy/process/_process_rq.py
Labels: bug, feature, improvement, refactor

#134 Remove some unused lines in OI code
  rqpy/limit/_limit.py
Labels: documentation, refactor, smallfix
