Repository ucbpylegroup/RQpy, pull requests merged in 2019-02, with the labels that each got.

#49 Replaced ds_trunc with improved function downsample_truncate
  rqpy/core/_pulse.py
Labels: improvement

#50 Added 2-pole nonlinear OF RQs
  rqpy/process/_process_rq.py
Labels: feature

#52 start pulse sim module
  rqpy/__init__.py
  rqpy/io/_io.py
  rqpy/sim/__init__.py
  rqpy/sim/_pulse_sim.py
Labels: feature

#57 Feature/ofnsmb
  rqpy/__init__.py
  rqpy/io/_io.py
  rqpy/process/_process_rq.py
  rqpy/sim/__init__.py
  rqpy/sim/_pulse_sim.py
Labels: feature

#62 Fixed bugs in Pulse Sim
  rqpy/io/_load.py
  rqpy/sim/_pulse_sim.py
Labels: bug, refactor

#63 Improvements to the Pulse Simulation
  rqpy/io/_load.py
  rqpy/io/_save.py
  rqpy/sim/_pulse_sim.py
Labels: feature, improvement, refactor

#64 Add the Trigger Simulation for mid.gz files
  .pre-commit-config.yaml
  rqpy/__init__.py
  rqpy/_globals.py
  rqpy/process/_process_rq.py
  rqpy/sim/__init__.py
  rqpy/sim/_trig_sim.py
Labels: feature
