Repository ucbpylegroup/RQpy, pull requests merged in 2019-04, with the labels that each got.

#92 Refactor plotting functions to have different folders
  rqpy/__init__.py
  rqpy/plotting/__init__.py
  rqpy/plotting/_core_plotting.py
  rqpy/plotting/_energy_cal_plotting.py
  rqpy/plotting/_fitting_plotting.py
  rqpy/plotting/_iv_didv_tools_plotting.py
  rqpy/plotting/_plotting.py
Labels: refactor

#95 Add more demos to RQpy
  demos/analysis/example_rq_analysis.ipynb
  demos/processing/make_template.ipynb
  demos/processing/process_IV_dIdV_sweep.ipynb
  demos/processing/process_data.ipynb
  demos/simulation/generate_sim_data.ipynb
Labels: documentation

#97 Hotfix for rq processing with no readout_inds
  rqpy/process/_process_rq.py
Labels: bug

#98 Add success/fail of OFnonlin to RQs
  rqpy/process/_process_rq.py
Labels: feature

#101 Add fix for using only the valid region of the FIR trace
  rqpy/sim/_trig_sim.py
Labels: bug

#100 Add conversion to ADC bins from arbitrary FPGA units
  rqpy/sim/_trig_sim.py
Labels: feature

#102 rp.limit.optimuminterval now sorts the eventenergies
  rqpy/limit/_limit.py
Labels: improvement, smallfix

#104 Fix unboundlocalerror in fit_gauss
  rqpy/core/_fitting.py
Labels: bug

#105 Feature/h5saving
  rqpy/io/_load.py
  rqpy/io/_save.py
Labels: feature

#106 Add more options for the integral RQ
  rqpy/process/_process_rq.py
Labels: improvement

#108 Add smear option to RatePlot plotting
  rqpy/limit/_limit.py
  rqpy/plotting/_core_plotting.py
Labels: feature

#107 Add support for changing rise/fall times in pulse simulation
  rqpy/sim/_pulse_sim.py
Labels: feature

#109 Specify direct convolve method in gauss_smear to avoid numerical errors
  rqpy/limit/_limit.py
Labels: bug

#110 Add smearing label to Gaussian smeared dRdE curves
  rqpy/plotting/_core_plotting.py
Labels: smallfix
