Repository ucbpylegroup/RQpy, pull requests merged in 2019-05, with the labels that each got.

#111 add Gaussian + asymmetric background fitting
  rqpy/core/_fitting.py
  rqpy/plotting/_fitting_plotting.py
  rqpy/utils/_utils.py
Labels: feature

#112 Add a file for storing constants
  rqpy/__init__.py
  rqpy/constants/__init__.py
  rqpy/constants/_constants.py
  rqpy/limit/_limit.py
Labels: refactor

#113 Add 2D Gaussian Smearing to OI Limit Code
  rqpy/limit/_limit.py
Labels: feature

#114 Calculate no delay amplitude for TrigSim, use windowcenter, update pileup processing
  rqpy/process/_process_rq.py
  rqpy/sim/_trig_sim.py
Labels: feature, improvement, refactor

#115 Add windowcenter to arg length check
  rqpy/process/_process_rq.py
Labels: bug, smallfix

#116 Add confidence ellipse plotting
  rqpy/plotting/_core_plotting.py
Labels: feature

#117 Fix x values definition in rqpy.limit.gauss_smear
  rqpy/limit/_limit.py
Labels: bug, smallfix

#118 Refactor and improve drde_gauss_smear2d
  rqpy/limit/_limit.py
Labels: bug, improvement, refactor
