Repository ucbpylegroup/RQpy, pull requests merged in 2019-03, with the labels that each got.

#72 Add cmap option and fix lgclognorm in rqpy.densityplot
  rqpy/plotting/_plotting.py
Labels: bug, feature

#73 Update RQ processing to make compatible with latest QETpy commits
  rqpy/process/_process_rq.py
Labels: bug

#79 Switch the order of the priors and non-priors dIdV fits in IVanalysis
  rqpy/core/_iv_didv_tools.py
Labels: smallfix

#74 Allow a list of paths to be passed to process_ivsweep
  rqpy/process/_process_iv_didv.py
Labels: smallfix

#80 Adding Passage Fraction Error Information
  rqpy/core/_cut.py
  rqpy/plotting/_plotting.py
Labels: feature

#81 fix optimum energy res calc, and plotting formatting
  rqpy/core/_iv_didv_tools.py
  rqpy/plotting/_plotting.py
Labels: bug, feature, improvement, refactor

#83 Add functional form for trigger efficiency
  rqpy/sim/_trig_sim.py
Labels: feature

#84 moved some plotting functionality to QETpy
  rqpy/core/_iv_didv_tools.py
  rqpy/plotting/_plotting.py
Labels: refactor

#87 Adding OI Limit functionality to RQpy
  rqpy/__init__.py
  rqpy/limit/__init__.py
  rqpy/limit/_limit.py
Labels: feature

#91 add trace scaling option to acquisition functions in trigger
  rqpy/process/_trigger.py
Labels: feature, smallfix

#90 Added the calculation of the Trigger Time to the TrigSim
  rqpy/process/_process_rq.py
  rqpy/sim/_trig_sim.py
Labels: feature

#89 Updated limit code to directly use UpperLimit Fortran code
  rqpy/limit/__init__.py
  rqpy/limit/_limit.py
  rqpy/limit/_upperlim/CERN_Stuff.f
  rqpy/limit/_upperlim/CLtable.txt
  rqpy/limit/_upperlim/CMaxf.in
  rqpy/limit/_upperlim/CMaxfLow.in
  rqpy/limit/_upperlim/CMaxinf.f
  rqpy/limit/_upperlim/Cinf.f
  rqpy/limit/_upperlim/ConfLev.f
  rqpy/limit/_upperlim/UpperLim.f
  rqpy/limit/_upperlim/upperlim.pyf
  rqpy/limit/_upperlim/y_vs_CLf.f
  rqpy/limit/_upperlim/y_vs_CLf.in
  rqpy/limit/_upperlim/ymintable.in
  setup.py
Labels: feature, improvement, refactor
