Repository ucbpylegroup/RQpy, pull requests merged in 2020-08, with the labels that each got.

#159 Update readme to recommend pip install .
  README.md
Labels: documentation

#160 use cdms rawio package rather than old scdmsPyTools interface
  rqpy/_globals.py
  rqpy/io/_load.py
  rqpy/io/_save.py
  rqpy/process/_process_iv_didv.py
  rqpy/process/_process_rq.py
  rqpy/sim/_pulse_sim.py
  setup.py
Labels: maintenance

#161 Update Stanford I/O Functions
  rqpy/io/_load.py
Labels: feature, maintenance
